### ISSUE TITLE
Instructions for linking to ANN via RANN2 package 

### ISSUE THREAD

**Issue by jefferis** [jefferis/RANN2#3]
@caiohamamura thanks again for your help. Could you edit the README to add a short section on linking to the package?

**Comment by caiohamamura** [comment]
OK, I will!

Em qui, 20 de jun de 2019 12:24, Gregory Jefferis <notifications@github.com>
escreveu:

**Comment by jefferis** [comment]
closed by 05d6eb285ed7b0f6d3b20b9a731fe0398e2954cb and 95fb31fa5c484907464735f057eaa8782a48ce9c
