### ISSUE TITLE
Can’t load the library in Rcpp

### ISSUE THREAD

**Issue by rvalavi** [jefferis/RANN2#9]
Hi @jefferis and @caiohamamura 
Thanks for providing such a useful library.

Is there any documentation or video on how to use your package in Rcpp? 
Using the header #include <ANN.h> doesn’t work for me. I have installed your package and even in the case of cloning the repo it doesn’t work 
https://github.com/jefferis/RANN2/blob/master/src/nn.cpp

I’ve tried this on Windows (for now).

I’m a bit new to Rcpp, I appreciate any hint or resources to be able to use your library in my Rcpp code.

**Comment by caiohamamura** [comment]
I have used it in an experimental package I was working on a while ago, you can check it out here https://github.com/caiohamamura/MeanShiftR/tree/RANN2.

I included it in the DESCRIPTION file within the linkingTo field, than the R will automatically add the headers file location for the linking packages, otherwise you will have to manually point to where the .h files are within your R library directory.

How are you planning to use it? 'Cause Rcpp had at least 3 different ways of working. 

This stackoverflow question may help you get there: https://stackoverflow.com/a/36354950

**Comment by rvalavi** [comment]
Thank you so much for the prompt response and for sharing the information, @caiohamamura.
That's great! I'll check them and try to solve the problem.

At the moment, I'm just trying to use it in a project which is not an R package. I want to use the ANN method to find KNN and perform radius searches in my C++ code.
I tried adding the complete address of `.h` file from the installed location of `RANN2` but it still didn't work. However, it was my first trial and I might have had other issues. I can give it a try with the new information you provided to see if I can solve the issue.

**Comment by caiohamamura** [comment]
For quick testing you can install the RANN2 package and then use this code:

```
# Point to where the shared library is "RANN2.dll" for Rcpp compilation
dllPath <- system.file(sprintf("libs/x64"), package = "RANN2")
Sys.setenv(PKG_LIBS = sprintf("-L\"%s\" -lRANN2", dllPath))

Rcpp::sourceCpp(
  code = "
// [[Rcpp::depends(RANN2)]]
#include <ANN/ANN.h>
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
int FindNearestNeighbor(NumericVector x, NumericVector y, double pt_x, double pt_y)
{
  const int n_dimensions = 2;
  int npts = x.length();

  ANNkd_tree *the_tree; // Search structure
  ANNpointArray data_pts = annAllocPts(npts, n_dimensions);
  ANNidxArray nn_idx = new ANNidx[npts];  // Allocate near neigh indices
  ANNdistArray dists = new ANNdist[npts]; // Allocate near neighbor dists
  
  // now construct the points
  for (int i = 0; i < npts; i++)
  {
    data_pts[i][0] = x[1];
    data_pts[i][1] = y[i];
  }

  the_tree = new ANNkd_tree(data_pts, npts, n_dimensions);

  // Construct the point query structure
  ANNpoint pt_query = annAllocPt(n_dimensions);
  pt_query[0] = pt_x;
  pt_query[1] = pt_y;

  // Search for the rearest neighbor
  the_tree->annkSearch(pt_query, 1, nn_idx, dists);

  int result = nn_idx[0];
  delete[] nn_idx;
  delete[] dists;
  delete the_tree;
  return result;
}
  "
)
x <- c(1, 50, 100)
y <- c(1, 50, 100)

FindNearestNeighbor(x, y, 2, -3) # Should return 0 (the 1st point (1,1))
FindNearestNeighbor(x, y, 40, 70) # Should return 1 (the 2nd point (50,50))
FindNearestNeighbor(x, y, 90, 170) # Should return 1 (the 3rd point (100,100))
```

**Comment by rvalavi** [comment]
Thank you so much for the clear example, @caiohamamura! It works like a charm! 👌
I can easily implement radius search as well.

Is there any way to use L1 distance (Manhattan) instead of L2 for KNN search?

I modified your example to return the k nearest neighbor. Not sure if there is a better way to convert `ANNidxArray` to a `std::vector<int>` but even with this for-loop should be fast enough.

```C++
// [[Rcpp::depends(RANN2)]]
#include <ANN/ANN.h>
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
NumericVector FindKNearestNeighbor(NumericVector x, NumericVector y, int k, double pt_x, double pt_y)
{
  const int n_dimensions = 2;
  int npts = x.length();

  ANNkd_tree *the_tree; // Search structure
  ANNpointArray data_pts = annAllocPts(npts, n_dimensions);
  ANNidxArray nn_idx = new ANNidx[npts];  // Allocate near neigh indices
  ANNdistArray dists = new ANNdist[npts]; // Allocate near neighbor dists
  
  // now construct the points
  for (int i = 0; i < npts; i++)
  {
    data_pts[i][0] = x[i];
    data_pts[i][1] = y[i];
  }

  the_tree = new ANNkd_tree(data_pts, npts, n_dimensions);

  // Construct the point query structure
  ANNpoint pt_query = annAllocPt(n_dimensions);
  pt_query[0] = pt_x;
  pt_query[1] = pt_y;

  // Search for the rearest neighbor
  the_tree->annkSearch(pt_query, k, nn_idx, dists);
  
  std::vector<int> result(k);
  for (int i = 0; i < k; i++)
  {
    result[i] = nn_idx[i];
  }
  delete[] nn_idx;
  delete[] dists;
  delete the_tree;
  return Rcpp::wrap(result);
}
 
```

**Comment by jefferis** [comment]
You need to recompile after modifying the header. See https://github.com/jefferis/RANN2/blob/4da9d640a46bd4b0ef538b127368fcf0e042b33d/inst/include/ANN/ANN.h#L350

**Comment by rvalavi** [comment]
Perfect! The L1 norm and p norm are already there 👌
Thank you so much, @jefferis!

Thank you both. I'm closing this issue then.

**Comment by rvalavi** [comment]
Just as a note if someone else wants to adopt this code; You need to add these couple of lines before the return line to avoid memory leaking (especially if you do a repeated search):

```C++
annDeallocPts(data_pts); 
annDeallocPt(pt_query);
```
